version: '3.9'

services:
  db:
    image: postgres:15
    container_name: yourfood-db
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 5

  bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: yourfood-bot
    restart: always
    env_file: .env.docker
    depends_on:
      db:
        condition: service_healthy

  admin:
    build:
      context: ./adminpanel
      dockerfile: Dockerfile
    container_name: yourfood-admin
    restart: always
    env_file: .env.docker
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8000:8000"

volumes:
  postgres_data:
